import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Image from "next/image";




export const metadata = {
  title: "A&B Distrubtors Account Manager Contact",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="flex flex-col bg-white dark:bg-gray-900 w-full h-screen">

        {children}
      </body>
    </html>
  );
}
